server:
  port: 8765

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://datafetcher
          predicates:
            - Path=/main/test
            - Method=GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka