server:
  port: 8765

spring:
  application:
    name: apigateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/monomicro-realm



  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: test
          uri: lb://datafetcher
          predicates:
            - Path=/api/v1/data-fetcher/monthly-report
            - Method=POST
        - id: data-fetcher-converter
          uri: lb://datafetcher
          predicates:
            - Path=/api/v1/data-fetcher/fetcher-converter
            - Method=POST
        - id: data-fetcher-storager
          uri: lb://datafetcher
          predicates:
            - Path=/api/v1/data-fetcher/fetcher-storager
            - Method=POST

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka